export const labels = {
  shopName: 'AMPER.GE',
  adminTitle: 'მაღაზიის მართვა',
  loginTitle: 'შესვლა',
  loginText: 'გაგრძელებისთვის შეხვიდეთ Google ანგარიშით.',
  loginButton: 'Google-ით შესვლა',
  signOut: 'გასვლა',
  tabs: { sales: 'გაყიდვები', newSale: 'ახალი გაყიდვა', stock: 'მარაგი', export: 'ექსპორტი' },
  forbidden: 'ეს ანგარიში არ არის დაშვებული.',
  rateLimited: 'ძალიან ბევრი მცდელობა, სცადეთ მოგვიანებით.',
  serverError: 'რაღაც წავიდა არასწორად, სცადეთ თავიდან.',
  retry: 'თავიდან სცადე',
  loading: 'იტვირთება…',
  empty: 'სია ცარიელია.',
  newSale: {
    batterySearch: 'ბატარეის ძებნა',
    batterySearchPlaceholder: 'სახელი, Ah, CCA, კორპუსი…',
    qty: 'რაოდენობა',
    unitPrice: 'ერთეულის ფასი (₾)',
    addLine: 'სხვა ბატარეის დამატება',
    removeLine: 'ხაზის წაშლა',
    soldOut: 'ამოწურულია',
    left: 'მარაგშია',
    customer: 'მომხმარებელი',
    firstName: 'სახელი',
    lastName: 'გვარი',
    idOrIban: 'პირადი ნომერი ან IBAN',
    idOrIbanHint: '9 ან 11 ციფრი, ან GE-ით დაწყებული IBAN.',
    idOrIbanError: 'შეიყვანეთ 9- ან 11-ციფრიანი ნომერი, ან სწორი IBAN.',
    phone: 'ტელეფონი (არასავალდებულო)',
    discount: 'ფასდაკლება (₾)',
    payment: 'გადახდის მეთოდი',
    cash: 'ნაღდი',
    transfer: 'გადარიცხვა',
    card: 'ბარათი',
    note: 'შენიშვნა (არასავალდებულო)',
    total: 'ჯამი',
    submit: 'გაყიდვის შენახვა',
    success: 'გაყიდვა შენახულია.',
    saleId: 'გაყიდვის ნომერი',
    again: 'ახალი გაყიდვა',
    pickBatteryFirst: 'ჯერ აირჩიეთ ბატარეა.',
  },
  sales: {
    from: 'დან',
    to: 'მდე',
    filter: 'ფილტრი',
    date: 'თარიღი',
    customer: 'მომხმარებელი',
    items: 'ნივთები',
    total: 'ჯამი',
    payment: 'გადახდა',
    status: 'სტატუსი',
    voidAction: 'გაუქმება',
    voidReason: 'გაუქმების მიზეზი',
    voidConfirm: 'გაყიდვის გაუქმება',
    voided: 'გაუქმებული',
    active: 'აქტიური',
    voidReasonShown: 'მიზეზი',
  },
  stock: {
    name: 'სახელი',
    spec: 'მახასიათებლები',
    quantity: 'რაოდენობა',
    status: 'სტატუსი',
    price: 'ფასი',
    cost: 'თვითღირებულება',
    in: 'მარაგშია',
    order: 'შეკვეთით',
    out: 'ამოწურულია',
    receive: 'მიღება',
    receiveQty: 'მიღებული რაოდენობა',
    unitCost: 'ერთეულის თვითღირებულება (₾, არასავალდებულო)',
    count: 'გადათვლა',
    countedQty: 'დათვლილი რაოდენობა',
    noteOptional: 'შენიშვნა (არასავალდებულო)',
    save: 'შენახვა',
    cancel: 'გაუქმება',
    noChange: 'რაოდენობა უკვე ეს არის.',
    notAvailable: '—',
    askForPrice: 'ფასი შეთანხმებით',
  },
  exportPanel: {
    sales: 'გაყიდვები (CSV)',
    stock: 'მარაგი (CSV)',
    movements: 'მოძრაობები (CSV)',
    hint: 'გაყიდვებსა და მოძრაობებს შეგიძლიათ თარიღებით გაფილტროთ.',
  },
} as const;

export type Labels = typeof labels;
